name: SwiftBot CI

on:
  push: { branches: [main] }

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build -c release
      - name: Run unit tests
        run: swift test
