version: '3.8'

services:
  kong:
    image: kong:3.3
    container_name: kong
    ports:
      - "8000:8000"   # Proxy
      - "8001:8001"   # Admin API
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml
    depends_on:
      - node-app
      - python-backend
      - dart-app

  node-app:
    build: ./node-app
    container_name: node-app
    expose:
      - "3000"

  python-backend:
    build: ./python-backend
    container_name: python-backend
    expose:
      - "5000"

  dart-app:
    build: ./dart-app
    container_name: dart-app
    expose:
      - "8080"
