version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: node:14
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npm start
    ports:
      - "5000:5000"
