version: "3.9"

services:
  node-app:
    build: ./Node-app
    ports:
      - "3000:3000"
    environment:
      - PYTHON_API_KEY=supersecretpythonkey
      - DART_API_KEY=supersecretdartkey
      - PYTHON_BACKEND_URL=http://python-backend:5000
      - DART_BACKEND_URL=http://dart-app:8080
    depends_on:
      - python-backend
      - dart-app

  python-backend:
    build: ./Python-backend
    environment:
      - PYTHON_API_KEY=supersecretpythonkey
    expose:
      - "5000"

  dart-app:
    build: ./Dart-app
    environment:
      - DART_API_KEY=supersecretdartkey
    expose:
      - "8080"
