version: '3.9'

services:
  nodeapp:
    build:
      context: ./node-app
    ports:
      - "3000:3000"
    depends_on:
      - pythonapp
      - dartapp

  pythonapp:
    build:
      context: ./python-backend
    ports:
      - "5000:5000"

  dartapp:
    build:
      context: ./dart-app
    ports:
      - "8080:8080"  # adjust if your Dart app serves HTTP
