version: "3.9"

services:
  kong:
    image: kong:3.6
    container_name: kong
    restart: always
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
    volumes:
      - ./kong/kong.yml:/usr/local/kong/declarative/kong.yml:ro
    depends_on:
      - node-app
      - python-backend
      - dart-app

  node-app:
    build:
      context: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    networks:
      - backend

  python-backend:
    build:
      context: ./python-backend
    container_name: python-backend
    ports:
      - "5000:5000"
    networks:
      - backend

  dart-app:
    build:
      context: ./dart-app
    container_name: dart-app
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
